<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="css/w3/w3.css">
        <link rel="icon" type="image/png" href="img/icon.png">
      <link rel="stylesheet" href="css/w3/w3-colors-2018.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Gestor T.I</title>
</head>
<body class="w3-2018-coconut-milk">
<header class="w3-container w3-2018-nebulas-blue">
    <div class="w3-container">
    <h3><b>Gestor T.I </b></h3>
        
 <div class="w3-row">
  <div class="w3-container w3-twothird"><p></p></div>
 <div class="w3-container w3-third">
     Primavera ©2021 Area TI
    </div>
    </div>
  </div> 
  </header> 
   <div class="w3-bar w3-2018-cherry-tomato w3-card">
  <a href="dashboard.php" class="w3-bar-item w3-button w3-border-right w3-hover-green"><b>Inicio</b></a>
  <a href="usuarios.php" class="w3-bar-item w3-button w3-border-right w3-hover-green">Gestor de usarios</a>
  <a href="registrototal.php" class="w3-bar-item w3-button w3-border-right w3-hover-green">Registro de ingresos</a>
  <a href="fx/logout.php" class="w3-bar-item w3-button w3-right w3-border-left w3-hover-green">Salir</a>
</div>

	
