<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="img/icon.png">
	<link rel="stylesheet" href="css/w3/w3.css">
  <link rel="stylesheet" href="css/w3/w3-colors-2018.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Gestor T.I</title>
</head>
<body>
	 <header class="w3-container w3-2018-nebulas-blue">
    <div class="w3-container">
    <h3><b>Gestor T.I </b></h3>
        
 <div class="w3-row">
  <div class="w3-container w3-twothird"><p></p></div>
 <div class="w3-container w3-third">
     Primavera ©2021 Area TI
    </div>
    </div>
  </div> 
  </header> 
 <div class="w3-bar w3-2018-cherry-tomato w3-card">
    <a href="dashboard.php" class="w3-bar-item w3-button w3-hover-green w3-border-right"><i class="fa fa-home"></i> &nbsp</a>

    <div class="w3-dropdown-hover">
      <button class="w3-button w3-border-right">Gestion de area    <i class="fa fa-info-circle" aria-hidden="true"></i></button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4 ">
        <a href="solicitudes.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Solicitudes T.I</a>
       <a href="prestamos.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Prestamo de equipos</a>
   <a href="directorio_ti.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Directorio de T.I</a>
    <a href="rutas.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Gestion de rutas</a>
    <a href="archivos.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Gestion archivos</a>
      </div>
    </div>

     <div class="w3-dropdown-hover">
      <button class="w3-button w3-border-right">Inventario <i class="fa fa-check-square-o" aria-hidden="true"></i></button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4 ">
         <a href="matriz.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Matriz de inventario</a>
  <a href="admin_inventario.php" class="w3-bar-item w3-button w3-hover-green w3-border-right">Maestro de inventario</a>     
      </div>
    </div>

  
     <a href="fx/logout.php" class="w3-bar-item w3-button w3-right w3-hover-red w3-border-left">Salir</a>
  </div>
</div>
	
